In [1]:
## import library
import pandas as pd

In [2]:
df = pd.read_csv("combined3.csv")
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,Unnamed: 6
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,NaN
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,NaN
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,NaN
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,NaN
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,NaN
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,NaN
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,NaN
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
cpi_start = df["cpi_away_food"].iat[0]
cpi_start

np.float64(275.893)

In [4]:
house_start = df["med_inc_house"].iat[0]
house_start

np.float64(77700.0)

In [5]:
chipotle_start = df["avg_chipotle"].iat[0]
chipotle_start

np.float64(14.07)

In [6]:
cava_start = df["avg_cava"].iat[0]
cava_start

np.float64(17.31)

In [7]:
sweetgreen_start = df["avg_sweetgreen"].iat[0]
sweetgreen_start

np.float64(14.39)

In [8]:
df["cpi_zero_index"] = df["cpi_away_food"].apply(lambda x:round((x-cpi_start)/cpi_start*100, 2))
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,Unnamed: 6,cpi_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,NaN,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,NaN,3.09
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,NaN,6.54
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,NaN,11.38
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,NaN,19.91
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,NaN,28.40
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,NaN,33.65
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,NaN,38.60
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df["house_zero_index"] = df["med_inc_house"].apply(lambda x:round((x-house_start)/house_start*100, 2))
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,Unnamed: 6,cpi_zero_index,house_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,NaN,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,NaN,3.09,7.16
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,NaN,6.54,4.99
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,NaN,11.38,4.59
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,NaN,19.91,2.32
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,NaN,28.40,6.42
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,NaN,33.65,7.76
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,NaN,38.60,9.60
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df["chipotle_zero_index"] = df["avg_chipotle"].apply(lambda x:round((x-chipotle_start)/chipotle_start*100, 2))
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,Unnamed: 6,cpi_zero_index,house_zero_index,chipotle_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,NaN,0.00,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,NaN,3.09,7.16,6.33
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,NaN,6.54,4.99,26.15
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,NaN,11.38,4.59,34.33
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,NaN,19.91,2.32,42.15
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,NaN,28.40,6.42,45.98
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,NaN,33.65,7.76,48.83
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,NaN,38.60,9.60,50.18
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.drop(columns=['Unnamed: 6'])
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,cpi_zero_index,house_zero_index,chipotle_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,0.00,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,3.09,7.16,6.33
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,6.54,4.99,26.15
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,11.38,4.59,34.33
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,19.91,2.32,42.15
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,28.40,6.42,45.98
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,33.65,7.76,48.83
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,38.60,9.60,50.18
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,cpi_zero_index,house_zero_index,chipotle_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,0.00,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,3.09,7.16,6.33
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,6.54,4.99,26.15
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,11.38,4.59,34.33
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,19.91,2.32,42.15
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,28.40,6.42,45.98
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,33.65,7.76,48.83
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,38.60,9.60,50.18
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df["cava_zero_index"] = df["avg_cava"].apply(lambda x:round((x-cava_start)/cava_start*100, 2))
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,cpi_zero_index,house_zero_index,chipotle_zero_index,cava_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,0.00,0.00,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,3.09,7.16,6.33,8.20
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,6.54,4.99,26.15,18.54
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,11.38,4.59,34.33,21.14
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,19.91,2.32,42.15,19.99
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,28.40,6.42,45.98,18.66
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,33.65,7.76,48.83,23.17
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,38.60,9.60,50.18,25.42
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df["sweetgreen_zero_index"] = df["avg_sweetgreen"].apply(lambda x:round((x-sweetgreen_start)/sweetgreen_start*100, 2))
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,cpi_zero_index,house_zero_index,chipotle_zero_index,cava_zero_index,sweetgreen_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,0.00,0.00,0.00,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,3.09,7.16,6.33,8.20,3.54
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,6.54,4.99,26.15,18.54,24.74
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,11.38,4.59,34.33,21.14,33.63
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,19.91,2.32,42.15,19.99,38.22
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,28.40,6.42,45.98,18.66,48.71
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,33.65,7.76,48.83,23.17,66.09
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,38.60,9.60,50.18,25.42,70.81
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,cpi_zero_index,house_zero_index,chipotle_zero_index,cava_zero_index,sweetgreen_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,0.00,0.00,0.00,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,3.09,7.16,6.33,8.20,3.54
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,6.54,4.99,26.15,18.54,24.74
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,11.38,4.59,34.33,21.14,33.63
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,19.91,2.32,42.15,19.99,38.22
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,28.40,6.42,45.98,18.66,48.71
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,33.65,7.76,48.83,23.17,66.09
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,38.60,9.60,50.18,25.42,70.81
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_clean = df.dropna()
df_clean

,date,cpi_away_food,med_inc_house,avg_chipotle,avg_cava,avg_sweetgreen,cpi_zero_index,house_zero_index,chipotle_zero_index,cava_zero_index,sweetgreen_zero_index
0,1/1/18,275.893,77700.0,14.07,17.31,14.39,0.00,0.00,0.00,0.00,0.00
1,1/1/19,284.410,83260.0,14.96,18.73,14.90,3.09,7.16,6.33,8.20,3.54
2,1/1/20,293.944,81580.0,17.75,20.52,17.95,6.54,4.99,26.15,18.54,24.74
3,1/1/21,307.296,81270.0,18.90,20.97,19.23,11.38,4.59,34.33,21.14,33.63
4,1/1/22,330.822,79500.0,20.00,20.77,19.89,19.91,2.32,42.15,19.99,38.22
5,1/1/23,354.256,82690.0,20.54,20.54,21.40,28.40,6.42,45.98,18.66,48.71
6,1/1/24,368.743,83730.0,20.94,21.32,23.90,33.65,7.76,48.83,23.17,66.09
7,1/1/25,382.378,85157.0,21.13,21.71,24.58,38.60,9.60,50.18,25.42,70.81

In [17]:
df_clean.to_csv('combined_analysis3.csv', index=False)