In [2]:
## import library
import pandas as pd

In [3]:
df = pd.read_csv("combined2.csv")
df

     date  cpi_away_food  med_inc_house  avg_chipotle
0  1/1/18        275.893          77700         14.07
1  1/1/19        284.410          83260         14.96
2  1/1/20        293.944          81580         17.75
3  1/1/21        307.296          81270         18.90
4  1/1/22        330.822          79500         20.00
5  1/1/23        354.256          82690         20.54
6  1/1/24        368.743          83730         20.94
7  1/1/25        382.378          85157         21.13

In [4]:
cpi_start = df["cpi_away_food"].iat[0]
cpi_start

np.float64(275.893)

In [5]:
house_start = df["med_inc_house"].iat[0]
house_start

np.int64(77700)

In [6]:
chipotle_start = df["avg_chipotle"].iat[0]
chipotle_start

np.float64(14.07)

In [7]:
df["cpi_zero_index"] = df["cpi_away_food"].apply(lambda x:round((x-cpi_start)/cpi_start*100, 2))
df

     date  cpi_away_food  med_inc_house  avg_chipotle  cpi_zero_index
0  1/1/18        275.893          77700         14.07            0.00
1  1/1/19        284.410          83260         14.96            3.09
2  1/1/20        293.944          81580         17.75            6.54
3  1/1/21        307.296          81270         18.90           11.38
4  1/1/22        330.822          79500         20.00           19.91
5  1/1/23        354.256          82690         20.54           28.40
6  1/1/24        368.743          83730         20.94           33.65
7  1/1/25        382.378          85157         21.13           38.60

In [8]:
df["house_zero_index"] = df["med_inc_house"].apply(lambda x:round((x-house_start)/house_start*100, 2))
df

,date,cpi_away_food,med_inc_house,avg_chipotle,cpi_zero_index,house_zero_index
0,1/1/18,275.893,77700,14.07,0.00,0.00
1,1/1/19,284.410,83260,14.96,3.09,7.16
2,1/1/20,293.944,81580,17.75,6.54,4.99
3,1/1/21,307.296,81270,18.90,11.38,4.59
4,1/1/22,330.822,79500,20.00,19.91,2.32
5,1/1/23,354.256,82690,20.54,28.40,6.42
6,1/1/24,368.743,83730,20.94,33.65,7.76
7,1/1/25,382.378,85157,21.13,38.60,9.60

In [9]:
df["chipotle_zero_index"] = df["avg_chipotle"].apply(lambda x:round((x-chipotle_start)/chipotle_start*100, 2))
df

,date,cpi_away_food,med_inc_house,avg_chipotle,cpi_zero_index,house_zero_index,chipotle_zero_index
0,1/1/18,275.893,77700,14.07,0.00,0.00,0.00
1,1/1/19,284.410,83260,14.96,3.09,7.16,6.33
2,1/1/20,293.944,81580,17.75,6.54,4.99,26.15
3,1/1/21,307.296,81270,18.90,11.38,4.59,34.33
4,1/1/22,330.822,79500,20.00,19.91,2.32,42.15
5,1/1/23,354.256,82690,20.54,28.40,6.42,45.98
6,1/1/24,368.743,83730,20.94,33.65,7.76,48.83
7,1/1/25,382.378,85157,21.13,38.60,9.60,50.18

In [10]:
df.to_csv('combined_analysis.csv', index=False)