In [2]:
## import library
import pandas as pd

In [3]:
## pull in data
df = pd.read_csv("combined1.csv")
df

       date  cpi_away_food  med_inc_pers  med_inc_house
0    1/1/16        262.695       39700.0        75380.0
1    1/1/17        268.826       40100.0        76710.0
2    1/1/18        275.893       41460.0        77700.0
3    1/1/19        284.410       43600.0        83260.0
4    1/1/20        293.944       43010.0        81580.0
..      ...            ...           ...            ...
868     NaN            NaN           NaN            NaN
869     NaN            NaN           NaN            NaN
870     NaN            NaN           NaN            NaN
871     NaN            NaN           NaN            NaN
872     NaN            NaN           NaN            NaN

[873 rows x 4 columns]

In [5]:
## delete empty rows
df = df.dropna()
df

     date  cpi_away_food  med_inc_pers  med_inc_house
0  1/1/16        262.695       39700.0        75380.0
1  1/1/17        268.826       40100.0        76710.0
2  1/1/18        275.893       41460.0        77700.0
3  1/1/19        284.410       43600.0        83260.0
4  1/1/20        293.944       43010.0        81580.0
5  1/1/21        307.296       43080.0        81270.0
6  1/1/22        330.822       43150.0        79500.0
7  1/1/23        354.256       43310.0        82690.0
8  1/1/24        368.743       45140.0        83730.0

In [ ]:
### Lambda expression, .iat = index at, holds a row value as an index starting point

In [14]:
### Hold CPI, median income, median house

cpi_start = df["cpi_away_food"].iat[0]
cpi_start

np.float64(262.695)

In [15]:
pers_start = df["med_inc_pers"].iat[0]
pers_start

np.float64(39700.0)

In [16]:
house_start = df["med_inc_house"].iat[0]
house_start

np.float64(75380.0)

In [17]:
## create a new column that holds the zero index for columns

df["cpi_zero_index"] = df["cpi_away_food"].apply(lambda x:round((x-cpi_start)/cpi_start*100, 2))
df

     date  cpi_away_food  med_inc_pers  med_inc_house  cpi_zero_index
0  1/1/16        262.695       39700.0        75380.0            0.00
1  1/1/17        268.826       40100.0        76710.0            2.33
2  1/1/18        275.893       41460.0        77700.0            5.02
3  1/1/19        284.410       43600.0        83260.0            8.27
4  1/1/20        293.944       43010.0        81580.0           11.90
5  1/1/21        307.296       43080.0        81270.0           16.98
6  1/1/22        330.822       43150.0        79500.0           25.93
7  1/1/23        354.256       43310.0        82690.0           34.85
8  1/1/24        368.743       45140.0        83730.0           40.37

In [18]:
df["pers_zero_index"] = df["med_inc_pers"].apply(lambda x:round((x-pers_start)/pers_start*100, 2))
df

,date,cpi_away_food,med_inc_pers,med_inc_house,cpi_zero_index,pers_zero_index
0,1/1/16,262.695,39700.0,75380.0,0.00,0.00
1,1/1/17,268.826,40100.0,76710.0,2.33,1.01
2,1/1/18,275.893,41460.0,77700.0,5.02,4.43
3,1/1/19,284.410,43600.0,83260.0,8.27,9.82
4,1/1/20,293.944,43010.0,81580.0,11.90,8.34
5,1/1/21,307.296,43080.0,81270.0,16.98,8.51
6,1/1/22,330.822,43150.0,79500.0,25.93,8.69
7,1/1/23,354.256,43310.0,82690.0,34.85,9.09
8,1/1/24,368.743,45140.0,83730.0,40.37,13.70

In [19]:
df["house_zero_index"] = df["med_inc_house"].apply(lambda x:round((x-house_start)/house_start*100, 2))
df

,date,cpi_away_food,med_inc_pers,med_inc_house,cpi_zero_index,pers_zero_index,house_zero_index
0,1/1/16,262.695,39700.0,75380.0,0.00,0.00,0.00
1,1/1/17,268.826,40100.0,76710.0,2.33,1.01,1.76
2,1/1/18,275.893,41460.0,77700.0,5.02,4.43,3.08
3,1/1/19,284.410,43600.0,83260.0,8.27,9.82,10.45
4,1/1/20,293.944,43010.0,81580.0,11.90,8.34,8.22
5,1/1/21,307.296,43080.0,81270.0,16.98,8.51,7.81
6,1/1/22,330.822,43150.0,79500.0,25.93,8.69,5.47
7,1/1/23,354.256,43310.0,82690.0,34.85,9.09,9.70
8,1/1/24,368.743,45140.0,83730.0,40.37,13.70,11.08

In [ ]:
## Already, CPI for food away from home has greatly outpaces both personal and household median annual income.